### PR TITLE
Add Rubocop to CI

### LINKED ISSUE #20: Turn on linting on the CI
Related to #17

### PR DESCRIPTION
**Pull request by jinjagit**
Closes #20

### CODE REVIEW

**Comment by jinjagit** [comment]
Rubocop now running in CI:  

rubocop_CI
  
- Tested with syntax error and CI failed with correct rubocop 'offense'.  
- After some experimentation, I opted for the [Rails way](https://github.com/rails/rails/blob/4a78dcb326e57b5035c4df322e31875bfa74ae23/.github/workflows/rubocop.yml#L1) as recommded for forked repos. in [Rubocop Linter Action](https://github.com/andrewmcodes/rubocop-linter-action)

**Comment by jinjagit** [comment]
I just noticed I missed an EOF newline. Is it OK if I correct this and push?

**Comment by jinjagit** [comment]
Now with added badge goodness:  
  
badges

**Review by oliverbarnes — APPROVED** [review]
Nice work 👌 Thanks man

**Pull request merged**
